### ISSUE TITLE
RimWorld v1.1 breaks this mod

### ISSUE THREAD

**Issue by God-damnit-all** [scuba156/WithoutSteam#1]
Here's an update guide. https://gist.github.com/pardeike/08ff826bf40ee60452f02d85e59f32ff

**Comment by scuba156** [comment]
Thanks for the heads up, I didn't notice an email notification for it until now. I'll update it sometime this weekend.

**Comment by scuba156** [comment]
Support for RimWorld v1.1 has now been added.

https://github.com/scuba156/WithoutSteam/releases/tag/v1.2
